sops:
  kms:
    - arn: arn:aws:kms:us-east-2:135541436944:key/cf81fa8f-bc07-4e15-aec8-7efbba591045
      aws_profile: komet

creation_rules:
  - path_regex: .*
    kms: arn:aws:kms:us-east-2:135541436944:key/cf81fa8f-bc07-4e15-aec8-7efbba591045
