apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-sample-app
  namespace: nlb-sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
          ports:
            - name: tcp
              containerPort: 80
          env:
            - name: PORT
              value: "80"
            {{- range $name, $value := .Values.deployment.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
