apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appLabel }}
    spec:
      containers:
        - name: {{ .Values.deployment.name | quote }}
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
          {{- if .Values.deployment.args }}
          command: [ "yarn" ]
          args: {{ .Values.deployment.args | toYaml | nindent 14 }}
          {{- end }}
          ports:
            - name: tcp
              containerPort: 80
          env:
            {{- range $name, $value := .Values.deployment.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
