apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nlb-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.deployment.image }}:{{ .Values.frontend.deployment.tag }}"
          ports:
            - name: tcp
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nlb-sample-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /app/index.html
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
  type: NodePort
  selector:
    app: frontend
