apiVersion: batch/v1
kind: Job
metadata:
  name: "migration-job-{{ .Values.deployment.tag }}"
spec:
  template:
    spec:
      containers:
      - name: migration
        image: "{{ .Values.job.image }}:{{ .Values.deployment.tag }}"
        env:
          {{- range $name, $value := .Values.job.env }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 200
