apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.service.healthcheckPath }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
  type: NodePort
  selector:
    app: {{ .Values.service.name }}
