helmDefaults:
  createNamespace: true

environments:
  default:
    values:
      - foo: bar

releases:
  - name: sample-app
    namespace: nlb-sample-app
    chart: ./test-service
    secrets:
      - ./test-service/secrets.yaml
