helmDefaults:
  createNamespace: true

environments:
  default:
    values:
      - env: prod

releases:
  - name: backend
    namespace: kmt-app
    chart: ./test-service
    secrets:
      - ./back-end/secrets.yaml
    values:
      - ./back-end/values.yaml
  - name: frontend
    namespace: kmt-app
    chart: ./test-service
    values:
      - ./front-end/values.yaml
