helmDefaults:
  createNamespace: true

environments:
  default:
    values:
      - ./environments/staging.yaml
    kubeContext: arn:aws:eks:us-east-1:135541436944:cluster/staging-kmt-cluster
  production:
    values:
      - ./environments/production.yaml
    kubeContext: arn:aws:eks:us-east-2:135541436944:cluster/production-kmt-cluster

releases:
  - name: backend
    namespace: kmt-app
    chart: ./microservice
    secrets:
      - ./back-end/secrets.yaml
    values:
      - ./back-end/values.yaml
  - name: frontend
    namespace: kmt-app
    chart: ./microservice
    values:
      - ./front-end/values.yaml
