clusterName: staging-kmt-cluster
controllerRoleARN: arn:aws:iam::135541436944:role/AmazonEKSLoadBalancerControllerRoleKmtStaging
# https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html
controllerImageRepository: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-load-balancer-controller
