repositories:
  - name: gitlab
    url: https://charts.gitlab.io
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: awspca
    url: https://cert-manager.github.io/aws-privateca-issuer
  - name: prometheus-comunity
    url: https://prometheus-community.github.io/helm-charts
    #- name: ingress-nginx
    #url: https://kubernetes.github.io/ingress-nginx

environments:
  default:
    values:
    - environment: production

releases:
  - name: prom
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
  - name: aws-load-balancer-controller
    installed: true
    chart: eks/aws-load-balancer-controller
    namespace: kube-system
    values:
      - aws-load-balancer-controller/values.yaml
  - name: aws-lb-serviceaccount
    installed: true
    chart: ./aws-lb-serviceaccount
    namespace: kube-system
    values:
      - controllerRoleARN: arn:aws:iam::135541436944:role/AmazonEKSLoadBalancerControllerRole
  - name: gitlab-agent
    installed: true
    namespace: gitlab-agent
    chart: gitlab/gitlab-agent
    values:
      - agent-config/values.yaml.gotmpl
    secrets:
      - agent-config/secrets.yaml
  - name: gitlab-agent-frontend
    namespace: gitlab-agent-frontend
    chart: gitlab/gitlab-agent
    values:
      - agent-config/values.yaml.gotmpl
    secrets:
      - agent-config/secrets-frontend.yaml
