repositories:
  - name: gitlab
    url: https://charts.gitlab.io
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

environments:
  default:
    values:
      - ./environments/staging/values.yaml
    secrets:
      - ./environments/staging/secrets.yaml
    kubeContext: arn:aws:eks:us-east-1:135541436944:cluster/staging-kmt-cluster
  production:
    values:
      - ./environments/production/values.yaml
    secrets:
      - ./environments/production/secrets.yaml
    kubeContext: arn:aws:eks:us-east-2:135541436944:cluster/production-kmt-cluster

releases:
  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/prometheus
    set:
      - name: "alertmanager.persistentVolume.storageClass"
        value: "gp2"
      - name: "server.persistentVolume.storageClass"
        value: "gp2"
  - name: grafana
    namespace: grafana
    chart: grafana/grafana
    set:
      - name: "alertmanager.persistentVolume.storageClass"
        value: "gp2"
      - name: "server.persistentVolume.storageClass"
        value: "gp2"
      - name: "persistence.enabled"
        value: true
      - name: "adminPassword"
        value: "EKS"
      - name: "service.type"
        value: "LoadBalancer"
  - name: aws-load-balancer-controller
    installed: true
    chart: eks/aws-load-balancer-controller
    namespace: kube-system
    values:
      - ./aws-load-balancer-controller/values.yaml
      - clusterName: {{ .Values.clusterName }}
      - image:
          repository: {{ .Values.controllerImageRepository }}
  - name: aws-lb-serviceaccount
    installed: true
    chart: ./aws-lb-serviceaccount
    namespace: kube-system
    values:
      - controllerRoleARN: {{ .Values.controllerRoleARN }}
  - name: gitlab-agent
    installed: true
    namespace: gitlab-agent
    chart: gitlab/gitlab-agent
    values:
      - agent-config/values.yaml.gotmpl
      - config:
          token: {{ .Environment.Values.backendAgentConfigToken }}
  - name: gitlab-agent-frontend
    namespace: gitlab-agent-frontend
    chart: gitlab/gitlab-agent
    values:
      - agent-config/values.yaml.gotmpl
      - config:
          token: {{ .Environment.Values.frontendAgentConfigToken }}
