# To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
#- name: traefik
#  url: https://charts.helm.sh/stable
repositories:
  - name: gitlab
    url: https://charts.gitlab.io
  - name: eks
    url: https://aws.github.io/eks-charts

environments:
    default:
      values:
        - foo: bar
          #secrets:
          #- baz: bar

releases:
  #- name: agent-config
  #namespace: gitlab-agent
  #chart: gitlab/gitlab-agent
  #values: agent-config/values.yaml
  #secrets: agent-config/secrets.yaml
- name: aws-load-balancer-controller
  chart: eks/aws-load-balancer-controller
  namespace: kube-system
  values:
    - aws-load-balancer-controller/values.yaml



# helm upgrade --install agent-config gitlab/gitlab-agent \
#    --namespace gitlab-agent \
#    --create-namespace \
#    --set image.tag=v15.2.0 \
#    --set config.token= \
#    --set config.kasAddress=wss://kas.gitlab.com
#
#    helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
#      -n kube-system \
#      --set clusterName=my-cluster \
#      --set serviceAccount.create=false \
#      --set serviceAccount.name=aws-load-balancer-controller
